name: Ansible Playbook CI/CD

on:
  push:
    paths:
      - '01_playbook_security.yml'
      - 'hosts'

jobs:
  run-playbook:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i hosts 01_playbook_security.yml --ask-vault-pass
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}