name: Ansible Playbook CI/CD

on:
  push:
    paths:
      - '01_playbook_security.yml'
      - 'hosts'

jobs:
  run-playbook:
    runs-on: self-hosted  # Exécuté directement sur ta VM Ansible

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Clone automatiquement le dépôt sur le runner

      - name: Copier les fichiers dans le dossier Ansible en excluant certains dossiers
        run: |
          rsync -av --delete --exclude='group_vars/' --exclude='vault/' . /home/ansible/DevOps_2025/

      - name: Create vault password file
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > /home/ansible/DevOps_2025/vault_password.txt

      - name: Run Ansible Playbook
        run: |
          cd /home/ansible/DevOps_2025
          ansible-playbook -i hosts 01_playbook_security.yml --vault-password-file vault_password.txt
        working-directory: /home/ansible/DevOps_2025  # Définit le répertoire de travail

      - name: Clean up
        run: rm /home/ansible/DevOps_2025/vault_password.txt
